apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: notifications.uptime.kuma
spec:
  group: uptime.kuma
  names:
    kind: Notification
    listKind: NotificationList
    plural: notifications
    singular: notification
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.status.status
      name: status
      priority: 0
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            nullable: false
            properties:
              status:
                nullable: false
                type: string
            type: object
          spec:
            nullable: false
            properties:
              type:
                nullable: true
                type: string
              url:
                nullable: true
                type: string
              webhookURL:
                nullable: true
                type: string
              isDefault:
                nullable: false
                type: boolean
              webhookContentType:
                nullable: false
                type: string
              applyExisting:
                nullable: false
                type: boolean
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}