apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "uptime-kuma-operator.fullname" . }}-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "uptime-kuma-operator.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "uptime-kuma-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}