{{- if .Values.uptimekuma.password }}
apiVersion: v1
kind: Secret
metadata:
  name: uptimekuma-secret
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  kuma_password: {{ .Values.uptimekuma.password | b64enc | quote }}
{{- end }}