kuma_load_all_ingress: true
uptimekuma:
  enabled: true
  image:
    tag: 1.23.13
  password: Test0!
  username: admin
  ingress:
    enabled: true
    extraLabels: {}
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
      nginx.ingress.kubernetes.io/server-snippets: "location / {\n  proxy_set_header\
        \ Upgrade $http_upgrade;\n  proxy_http_version 1.1;\n  proxy_set_header X-Forwarded-Host\
        \ $http_host;\n  proxy_set_header X-Forwarded-Proto $scheme;\n  proxy_set_header\
        \ X-Forwarded-For $remote_addr;\n  proxy_set_header Host $host;\n  proxy_set_header\
        \ Connection \"upgrade\";\n  proxy_set_header X-Real-IP $remote_addr;\n  proxy_set_header\
        \ X-Forwarded-For $proxy_add_x_forwarded_for;\n  proxy_set_header   Upgrade\
        \ $http_upgrade;\n  proxy_cache_bypass $http_upgrade;\n}\n"
    hosts:
      - host: uptime.test.example.co.za
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - uptime.test.example.co.za
        secretName: uptime-tls-secret
autoscaling:
  enabled: false
labels: {}
image:
  repository: ghcr.io/jasonrve/uptime-kuma-operator
  pullPolicy: Always
  tag: 0.1.2
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
resource: {}
