apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: httpmonitors.uptime.kuma
spec:
  group: uptime.kuma
  names:
    kind: HttpMonitor
    listKind: HttpMonitorList
    plural: httpmonitors
    singular: httpmonitor
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.status.status
      name: status
      priority: 0
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            nullable: false
            properties:
              test:
                nullable: false
                type: string
            type: object
          spec:
            nullable: false
            properties:
              type:
                nullable: true
                type: string
              url:
                nullable: true
                type: string
              method:
                nullable: false
                type: string
              interval:
                format: int32
                nullable: false
                type: integer
              retryInterval:
                format: int32
                nullable: false
                type: integer
              resendInterval:
                format: int32
                nullable: false
                type: integer
              maxretries:
                format: int32
                nullable: false
                type: integer
              timeout:
                format: int32
                nullable: false
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}